Feat: Add hourly bonus chart to monitoring daily difference
pt-plugins/PT-Plugin-Plus pull request #1509
Opened 2023-07-29 10:59 UTC by Meng-Lan

添加一个时魔的图表，用来观察时魔趋势。

2023-07-29 11:02 UTC, Meng-Lan commented
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29281728/a346e1a0-d045-453c-8e47-2770db46d03a)

2023-09-02 16:02 UTC, IITII approved these changes

2023-09-02 16:07 UTC, IITII requested changes

2023-09-02 16:07 UTC, IITII commented on src/options/views/statisticCharts/SiteBase.vue
> +      <highcharts :options="chartBounsData" class="mt-4" />
这种个折线图是不是好点？石墨这种东西看的更多是应该是趋势吧？

2023-09-03 03:09 UTC, Meng-Lan commented on src/options/views/statisticCharts/SiteBase.vue
> +      <highcharts :options="chartBounsData" class="mt-4" />
有可能，没试过。
目前的堆叠效果还可以，一个是看总量，高度是否一致。不符合预期再看分量哪部分少了。
对于保种来说，一种是连接断了，另一种是站点调整了计算的数值。

2023-09-03 03:20 UTC, IITII commented on src/options/views/statisticCharts/SiteBase.vue
> +      <highcharts :options="chartBounsData" class="mt-4" />
在想了一下，如果是折线的话，可能线很多，看不清楚

2023-09-03 03:24 UTC, IITII approved these changes

2023-09-03 03:45 UTC, IITII commented
还是需要折线图的，不过是石墨总和的折线，不需要按站点展示。能否做成 这种 复合的图？https://iitii.github.io/VNSTAT-DASHBOARD/#/

* 折线显示 石墨总和，下面的柱状图可以保留目前的显示形式 @Meng-Lan 

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/7e9a550e-6f51-44af-a955-32d728ef0a90)

2023-09-03 03:48 UTC, IITII requested changes
再加个折线图吧，显示石墨总和的折线，不需要按站点展示。柱状图保留现在的展示形式就行。
从主观上更直观，想看详细变动可以再移到柱状图上。
能否做成 这种 复合的图？https://iitii.github.io/VNSTAT-DASHBOARD/#/

* 折线显示 石墨总和，下面的柱状图可以保留目前的显示形式 @Meng-Lan 

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/7e9a550e-6f51-44af-a955-32d728ef0a90)

2023-09-03 04:38 UTC, Meng-Lan commented
> 再加个折线图吧，显示石墨总和的折线，不需要按站点展示。柱状图保留现在的展示形式就行。 从主观上更直观，想看详细变动可以再移到柱状图上。 能否做成 这种 复合的图？https://iitii.github.io/VNSTAT-DASHBOARD/#/
> 
> ![image](https://user-images.githubusercontent.com/33705067/265240833-7e9a550e-6f51-44af-a955-32d728ef0a90.png)
因为本身是堆叠在一起的，所以总量的趋势也还算明显?
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29281728/bc63a328-83cd-46c0-a891-e5903bd42439)

2023-09-03 05:50 UTC, IITII approved these changes

2023-09-03 05:51 UTC, merged