feat(Home):  Change the ` lastUpdateTime` format to relative time.
pt-plugins/PT-Plugin-Plus pull request #1590
Opened 2023-09-17 14:48 UTC by lqzhgood

将首页的 最后一次数据更新时间 修改为相对时间，绝对时间放置到 title 里面

before
![268508887-dfc67dec-82c1-47c5-bf59-c05c8c7ef114](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9134671/1e2e246a-f652-43b5-913e-99ef42b4eab9)

after
![268508708-29c77eb0-ad48-4442-a956-4f8baea8b9d2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9134671/6d0b5ee4-2de5-464b-9ee6-c40111a4fea6)

2023-09-17 18:12 UTC, IITII commented
建议做成这种 
<img width="249" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/28ef4bc1-9f69-44b5-a904-109343ba1e06">

2023-09-17 18:13 UTC, IITII commented on src/options/views/Home.vue
> +          align: "center",
而且改成 相对时间, 字符串长短不一,应该右对齐

2023-09-17 18:14 UTC, IITII requested changes
配置成开关, 可切换

2023-09-18 01:31 UTC, lqzhgood commented
#### 对齐方式
- 右对齐试过了~ 非常丑，因为相对时间是个文本描述，且长度基本一致
- 因为这里并不存在 单行数据更新的情况，（刷新我的数据 -> 全部更新），所以这里的时间大部分情况也是一样的，即便因为某行更新失败导致数值不一样，到下一次更新时间，这段时间也不会差出一个数量级

所以我认为居中更合适


#### 是否需要做成选项
基于这个数据的内容是 `最后的更新时间`

- 大家看到这个数据其实只关心距离现在的相对时间 （这个数据是否太旧，需要我去更新）
- 更新的这个 __时刻__ （绝对时间）其实没有太多意义。（我并不需要通过这个时刻去联想到其他事情）

所以我认为 __相对时间__ 应该是一个默认选项，而 __绝对时间__ 因为并没有太多意义，不需要做成选项让其可以一直显示，但基于方便，放到 `title` 中即可

2023-09-18 05:13 UTC, IITII commented
* 对齐方式
  * 截个图看看吧, 这块感觉和入站时间一样, 还是右对齐好点
* 是否需要做成选项
  * 因为显示 相对时间还是绝对时间, 这个问题本身就是有争议的. 所以目前做成开关好点.
  * 这个会影响排序吗?

2023-09-18 07:11 UTC, lqzhgood commented
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9134671/b20731d2-56ad-4ca6-8544-4307a680e88f)

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9134671/b3fea446-17de-4ca5-9d23-bea26152f422)


右对齐是为了基于数字，上下对比大小，最后一次更新并不需要对比~
即便是使用 绝对时间， 因为时间格式 `YYYY-MM-DD HH:mm:ss` 保证长度一致 也不需要右对齐来对比。

2023-09-18 11:37 UTC, IITII commented
1. 关于对齐的问题, 你可以看看这个 #1260
2. 改成相对时间会影响排序吗?

2023-09-18 11:53 UTC, lqzhgood commented
不影响排序，只修改了view中的数据显示，未涉及数据排序

2023-09-18 16:03 UTC, IITII approved these changes

2023-09-18 16:03 UTC, IITII commented on src/options/views/Home.vue
> +          <td v-if="showColumn('user.lastUpdateTime')" class="center">
试了一下, 居中只和这个有关... (没发现你上面发的对比图都是一样的吗
样式上居中确实是比其他好点

2023-09-18 16:06 UTC, IITII commented on src/options/views/Home.vue
> +          <td v-if="showColumn('user.lastUpdateTime')" class="center">
选项你看着加吧, 默认启用就行. 不好加或者加完了, @我 merge 就行

2023-09-19 01:50 UTC, lqzhgood commented
因为最后更新时间的字符串长度一致（10分钟前），所以看不太出来
我是2k屏，全屏下右对齐会让左边间距非常大，就会非常明显，截图不放大到100%很难感觉。

增加了选项，默认开启
![屏幕截图 2023-09-19 094351](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9134671/401454d9-d490-4588-a8dd-27b9014d9efb)

2023-09-19 01:53 UTC, merged