Update CGPeers' host and cdn
pt-plugins/PT-Plugin-Plus pull request #1620
Opened 2023-10-10 11:21 UTC by likevi9528

www.cgpeers.com is 301 to cgpeers.to
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/81839775/b1486afe-56dc-42fc-be2b-df4af002c22b)

2023-10-20 05:27 UTC, IITII commented
使用 formerHosts 和 cdn 进行修改, 具体参考 mteam 的配置
<img width="841" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/03283eb0-a9fa-48ad-ba69-81fa57788b5a">

2023-10-22 02:18 UTC, likevi9528 commented
已参考 mteam 配置修改

2023-10-23 02:17 UTC, IITII requested changes

2023-10-23 02:17 UTC, IITII commented on resource/sites/cgpeers.to/config.json
> +  "cdn": ["https://cgpeers.to/","https://www.cgpeers.to/"],
cdn 填写错误

2023-10-23 02:47 UTC, likevi9528 commented on resource/sites/cgpeers.to/config.json
> +  "cdn": ["https://cgpeers.to/","https://www.cgpeers.to/"],
没错的，cgpeers.to（主）和www.cgpeers.to都能访问，只不过com的弃用了。

2023-10-24 02:58 UTC, IITII commented on resource/sites/cgpeers.to/config.json
> +  "cdn": ["https://cgpeers.to/","https://www.cgpeers.to/"],
应该改成 `"cdn": ["https://cgpeers.to/","https://www.cgpeers.to/","https://www.cgpeers.com/"]`,

2023-10-25 02:28 UTC, IITII approved these changes

2023-10-25 02:29 UTC, merged