fix(pter): 更正 levelName 及匹配规则
pt-plugins/PT-Plugin-Plus pull request #1728
Opened 2024-02-19 07:53 UTC by echo094

目前本站的等级名称在简中及繁中下为中文+全大写英文，在英语下为首字母大写英文，故修改等级名称为全大写，并添加对应的 levelName 选择器。

2024-02-19 08:52 UTC, IITII requested changes

2024-02-19 08:52 UTC, IITII commented on resource/sites/pterclub.com/config.json
> +    "name": "POWER USER",
* 英文的等级无需修改

2024-02-19 08:52 UTC, IITII commented on resource/sites/pterclub.com/config.json
> +        },
这块修改这和之前有什么区别吗? 改进在哪?

2024-02-19 08:57 UTC, echo094 commented on resource/sites/pterclub.com/config.json
> +    "name": "POWER USER",
目前的比较代码对于大小写敏感，不修改无法正确匹配。

2024-02-19 09:06 UTC, echo094 commented on resource/sites/pterclub.com/config.json
> +        },
也可以通过修改 https://github.com/pt-plugins/PT-Plugin-Plus/blob/7708c8d9e67136604a6ce70481f7ce7c69a04764/src/options/views/Home.vue#L713 解决这一问题：

```javascript
user.levelName.toUpperCase() == levelRequirement.name.toUpperCase()
```

这样的话会影响其它网站（但应该不会产生负面影响，并且能够解决其它网站的同类问题）

2024-02-20 08:22 UTC, IITII commented on resource/sites/pterclub.com/config.json
> +        },
只改 Home.vue 吧, 你本地验证下

2024-02-20 08:35 UTC, closed without merging