fix:rousi LevelRequirements
pt-plugins/PT-Plugin-Plus pull request #1755
Opened 2024-03-16 08:27 UTC by vicjl

2024-03-16 08:48 UTC, vicjl commented
![屏幕截图 2024-03-16 164802](https://github.com/pt-plugins/PT-Plugin-Plus/assets/43945856/ce13693e-edc2-468c-8665-8053c8d7c387)

2024-03-18 07:14 UTC, IITII requested changes
等级名称修改建议:
1. 优先以 NexusPHP 原版等级名称, PU, NU 为准, 作为统一
2. 个人详情, 等级图标的标题如果修改过, 比如 hdsky. 则等级名称以这个为准, 如果可以和 NexusPHP 对应上, 则应同时备注. 如: `临时演员/User` 或者 ` 跑龙套(Power User)`

2024-03-18 12:00 UTC, vicjl commented
> 等级名称修改建议:
> 
> 1. 优先以 NexusPHP 原版等级名称, PU, NU 为准, 作为统一
> 2. 个人详情, 等级图标的标题如果修改过, 比如 hdsky. 则等级名称以这个为准, 如果可以和 NexusPHP 对应上, 则应同时备注. 如: `临时演员/User` 或者 ` 跑龙套(Power User)`

您好，以上站点情况如下：
rousi：等级提升条件变更
zmpt：等级图标、文字变更，但存在对应关系
HDCity：等级文字变更，ptpp获取到的等级信息样式为：权天使(Elite Angel)
SSD：等级文字变更，ptpp获取到的等级信息样式为：发烧
M-Team：存在对应关系，等级标题变更
CHD：等级标题变更，但ptpp获取到的信息维持原样
JoyHD：新添加等级要求
HDPost：新添加等级要求
主要是我没有hdsky，所以我不清楚您举的例子他等级条件是啥样的 LOL
烦请指出不适合修改等级名称的站点，我来修改回去，谢谢

2024-03-19 02:51 UTC, IITII commented
zmpt: 无需修改
HDCity: 权天使/Elite Angel
SSD: 入门/Power User
CHD: 无需修改
mt: 无需修改

其他的改了就不需要动了

2024-03-19 02:54 UTC, IITII requested changes

2024-03-19 02:54 UTC, IITII commented on resource/sites/joyhd.net/config.json
> +  "collaborator": "ylxb2016 & add Level Requirments by VicQ",
这是个数组, 只需要写用户名. 参考其他配置文件

2024-03-19 12:00 UTC, vicjl commented on resource/sites/joyhd.net/config.json
> +  "collaborator": "ylxb2016 & add Level Requirments by VicQ",
已修改

2024-03-19 12:00 UTC, vicjl commented
已修改完成

2024-03-19 15:25 UTC, IITII requested changes

2024-03-19 15:25 UTC, IITII commented on resource/sites/pt.hdpost.top/config.json
> +  ],
这两逗号应该删掉吧?

2024-03-20 14:53 UTC, IITII requested changes

2024-03-20 14:53 UTC, IITII commented on resource/sites/pt.hdpost.top/config.json
> +      "name": "白银(PowerUser)",
ptpp 获取到的等级名称格式是什么?

2024-03-20 14:53 UTC, IITII commented on resource/sites/joyhd.net/config.json
> +      "name": "副参领(VeteranUser)",
ptpp 获取到的等级名称格式是什么?

2024-03-20 15:15 UTC, vicjl commented on resource/sites/pt.hdpost.top/config.json
> +      "name": "白银(PowerUser)",
仅英文“User”

2024-03-20 15:15 UTC, vicjl commented on resource/sites/joyhd.net/config.json
> +      "name": "副参领(VeteranUser)",
仅中文，“平民”

2024-03-21 07:55 UTC, IITII commented on resource/sites/pt.hdpost.top/config.json
> +      "name": "白银(PowerUser)",
那这个只需要 `Power User` 这种格式即可

2024-03-21 07:55 UTC, IITII commented on resource/sites/joyhd.net/config.json
> +      "name": "副参领(VeteranUser)",
格式: `副参领/Veteran User`

2024-03-27 03:04 UTC, closed without merging