fix(ptt): disable imdb search
pt-plugins/PT-Plugin-Plus pull request #1837
Opened 2024-05-03 20:54 UTC by trim21

禁用ptt的imdb搜索功能。这网站不仅搜不出结果还搜出一堆无关结果来造成污染。

修复imdb搜索时如果所有网站都不支持imdb搜索，一直显示loading状态的问题

2024-05-04 15:30 UTC, IITII requested changes

2024-05-04 15:30 UTC, IITII commented on src/options/views/search/SearchTorrent.ts
> +      const q = sites.filter((site: Site) => {
...这个 q 也太随意了，filter 后面加 forEach就行

2024-05-04 15:31 UTC, trim21 commented on src/options/views/search/SearchTorrent.ts
> +      const q = sites.filter((site: Site) => {
要检查length的，好像没法串起来

2024-05-05 06:30 UTC, IITII requested changes

2024-05-05 06:30 UTC, IITII commented on src/options/views/search/SearchTorrent.ts
> +      const q = sites.filter((site: Site) => {
那 q 改个确切点的变量名吧

2024-05-05 11:51 UTC, merged