feat (searcher): 增加 `searchEntryConfig.area` 禁用功能、`keyAutoMatch` 正则 Unicode 支持
pt-plugins/PT-Plugin-Plus pull request #1860
Opened 2024-05-11 14:27 UTC by davidxuang

#1814 的前置 PR。

按先前讨论，拟藉由 `searchEntryConfig.area` 实现目标功能，包括：
* 增加一处为站点禁用所有 `searchEntryConfig.area` 的选项；
* 为 `keyAutoMatch` 正则增加 `u` flag，启用 Unicode 支持；
* 将 `searchEntryConfig.area` 替换后的搜索词打印到控制台。

2024-05-13 06:55 UTC, IITII requested changes
1. 这个命名怎么是 搜索域? 从功能上理解的话应该是 `启用关键词精确匹配`
2. 设置界面, 关键词替换日志, 统一关键词开启关闭 `关键词精确匹配` 的 对比截图
3. 空格 之类的 code style 的修改撤回. 每个人 code style 不一样, diff 看起来太费劲了

2024-05-13 14:43 UTC, davidxuang commented
> 1. 这个命名怎么是 搜索域? 从功能上理解的话应该是 `启用关键词精确匹配`

确实，不过这是按照 `area` 挪过来的，这个命名本身对于这个功能来说范围太小了。改成“替换”了，“精确匹配”听上去是 Google 加双括号的那个功能。

2024-05-13 14:54 UTC, davidxuang commented
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/b5533d57-7ac0-4bc7-a3b1-a8e1a704f8cf)

## Sample: should transform

### Enabled

![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/a9bb7d84-b3f7-4aac-bce7-a7830e332487)
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/8cd843e7-e040-4e9f-8430-c3dcebf6273f)

### Disabled

![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/be3d0255-2dd6-4280-bc8d-cacd38626c39)

## Sample: should not transform

![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/01c353c6-b976-465a-8cb8-866e5f1a32a3)
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/24728204/9239cec3-bf7d-484d-8ded-289339fe9104)

2024-05-14 03:06 UTC, IITII approved these changes

2024-05-14 03:22 UTC, merged