fix (btschool):修复数据获取
pt-plugins/PT-Plugin-Plus pull request #1867
Opened 2024-05-15 13:47 UTC by SHL-COOL

#1863 
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/31879581/1b9b93a9-5907-4b39-b657-8261ec789ec5)

修复后，测试可以正常获取
**需要先点开一次网站**

2024-05-15 14:30 UTC, IITII commented on src/background/user.ts
> +        this.getAllCookies(url,"https://btschool.club", (cookies) => {
改成 activeURL

2024-05-15 14:31 UTC, IITII requested changes

2024-05-15 14:31 UTC, IITII commented on src/background/user.ts
> +      }else{
这个 code style,,,

2024-05-15 14:52 UTC, fzlins commented
这种核心功能的改动先不要merge，等pre-release发布后再说。

2024-05-16 10:36 UTC, SHL-COOL commented on src/background/user.ts
> +      }else{
快速编码是粗暴了些😆

2024-05-16 10:37 UTC, SHL-COOL commented on src/background/user.ts
> +      }else{
> 这个 code style,,,

快速编码是粗暴了些😆

2024-05-16 10:45 UTC, SHL-COOL commented on src/background/user.ts
> +      }else{
不急合并，有时间可以帮忙改一改

2024-05-21 14:47 UTC, G1t-hub commented
刚才测试点开网站及个人信息页再刷新还是报错，浏览能过cf盾但是刷新数据还是过不了
Debugger信息如下：
1 | 2024/5/21 22:25:51 | requestMessage.getUserInfo
2 | 2024/5/21 22:25:52 | [BTSCHOOL]网络请求失败！(403 , error)
3 | 2024/5/21 22:25:52 | pt.btschool.club
4 | 2024/5/21 22:25:52 | https://pt.btschool.club/index.php
5 | 2024/5/21 22:25:52 | <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="X-UA-Compatible" content="IE=Edge">...</head>
<body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">**Enable JavaScript and cookies to continue**</span></div></div></noscript></div></div><script>...</script></body></html>
6 | 2024/5/21 22:25:52 | requestMessage.writeLog
7 | 2024/5/21 22:25:52 | requestMessage.readConfig

2024-05-22 17:02 UTC, fzlins commented
@IITII 吴昊，还是你看吧

2024-05-28 09:16 UTC, closed without merging