fix(m-team):使用api域名
pt-plugins/PT-Plugin-Plus pull request #1917
Opened 2024-06-22 07:00 UTC by SHL-COOL

#1913 
用户数据和种子页切换为api域名
![2024_6_22 14_56_03](https://github.com/pt-plugins/PT-Plugin-Plus/assets/31879581/dd07d8f1-e6a9-47a6-9b15-5a41af2591d7)

2024-06-23 11:46 UTC, SHL-COOL commented
> #1913 用户数据和种子页切换为api域名 ![2024_6_22 14_56_03](https://private-user-images.githubusercontent.com/31879581/341947649-dd07d8f1-e6a9-47a6-9b15-5a41af2591d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDM0NTAsIm5iZiI6MTcxOTE0MzE1MCwicGF0aCI6Ii8zMTg3OTU4MS8zNDE5NDc2NDktZGQwN2Q4ZjEtZTZhOS00N2E2LTliMTUtNWE0MWFmMjU5MWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExNDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTNiOTZkYmMyMTNiODQzZmYxMDkzODE1YmQ3MTZhMmJhYmM5N2JlMTBiZDA0Y2I0OTkwMjA0ZDI4OGVjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVEpmTNpgemfFEhqHSbLUSrKxlY6ZfHdmQvsd2-_SXA)

**需要重新添加站点**

2024-06-25 03:12 UTC, IITII requested changes
1. api 域名有多个
2. 和 CDN 一样, api 域名 在添加站点页面应该可以修改
3. cdn 里面不需要写 api 域名

2024-06-25 05:17 UTC, SHL-COOL commented
> 3. cdn 里面不需要写 api 域名

2024-06-25 05:18 UTC, SHL-COOL commented
> 3. cdn 里面不需要写 api 域名
种子页下载到有判断 cdn,不然匹配不到下载器

2024-06-25 05:19 UTC, SHL-COOL commented
> 1. api 域名有多个
> 2. 和 CDN 一样，在添加站点页面时应该可以修改 api 域名
> 3. cdn 里面不需要写 api 域名

种子页下载到 有匹配cdn，不然没有下载器

2024-06-26 08:13 UTC, IITII commented
@SHL-COOL `种子页下载到 有匹配cdn` 这句话怎么理解? 我记得之前就是正常的. 网站 CDN 和 API CDN 本身就属于独立的设置, 不应该相互干扰.

2024-06-26 08:28 UTC, SHL-COOL commented
> @SHL-COOL `种子页下载到 有匹配cdn` 这句话怎么理解? 我记得之前就是正常的. 网站 CDN 和 API CDN 本身就属于独立的设置, 不应该相互干扰.

现在没问题了

2024-06-27 03:02 UTC, IITII approved these changes

2024-06-27 03:02 UTC, merged