feat: add lgs
pt-plugins/PT-Plugin-Plus pull request #2053
Opened 2024-11-13 07:10 UTC by haowenwu

2024-11-13 12:47 UTC, haowenwu commented
![tmp2601](https://github.com/user-attachments/assets/f5ab0494-525d-490f-b46c-c74b055ef5ca)

2024-11-19 05:52 UTC, IITII requested changes

2024-11-19 05:52 UTC, IITII commented on resource/sites/ptlgs.org/config.json
> +  }, {
没有等级对应的权益吗?

2024-11-19 06:02 UTC, closed without merging

2024-11-19 06:02 UTC, haowenwu commented
已经有新的 PR 了